#!/usr/bin/env python
# -*- coding: utf-8 -*-

my_articles = [
    "Química.",
    "Química ambiental.",
    "Química en México.",
    "Química de los alimentos.",
    "Química medicinal.",
    "Química industrial.",
    "Propiedad química.",
    "Industria química.",
    "Instituto Nacional de Estadística y Geografía (INEGI).",
    "Nutracéutico.", 
    "Propiedades físicas del diamante.",
    "Cinética.",
    "Teoría cinética.",
    "Líquido.",
    "Sólido.",
    "Gas.",
    "Propiedades intensivas y extensivas.",
    "Masa.",
    "Kilogramo por metro cúbico.",
    "Densidad.",
    "Balanza.",
    "Volumen.",
    "Instrumento de medición.",
    "Metro cúbico.",
    "Densidad.",
    "Propiedades intensivas y extensivas.",
    "Temperatura.",
    "Punto de ebullición.",
    "Elevación del punto de ebullición.",
    "Punto de fusión.",
    "Viscosidad.",
    "Viscosímetro.",
    "Viscoelasticidad.",
    "Viscosa.",
    "Unidades de viscosidad.",
    "Densidad.",
    "Solubilidad.",
    "Equilibrio de solubilidad.",
    "Producto de solubilidad.",
    "Disolución.",
    "Disolución acuosa.",
    "Mezcla.",
    "Sistema heterogéneo.",
    "Sistema homogéneo.",
    "Coloide.",
    "Disolución.",
    "Soluto.",
    "Disolvente.",
    "Polaridad de un disolvente.",
    "Concentración porcentual en volumen.",
    "Concentración.",
    "Saladino.",
    "Mezcla.",
    "Métodos de separación de fases.",
    "Proceso de separación.",
    "Filtración.",
    "Filtración a vacío.",
    "Decantación.",
    "Embudo de decantación.",
    "Cambio de estado.",
    "Destilación.",
    "Destilación simple.",
    "Destilación fraccionada.",
    "Balón de destilación.",
    "Centrifugación.",
    "Centrifugadora.",
    "Cristalización.",
    "Cristalizador.",
    "Contaminación.",
    "Contaminación hídrica.",
    "Contaminación del suelo.",
    "Contaminación tóxica del agua.",
    "Como ayudar a detener la contaminación.",
    "Concentración.",
    "Lluvia ácida.",
    "Toxina botulínica.",
    "Toxicidad.",
    "Alquimia.",
    "Símbolo alquímico.",
    "Antoine Lavoisier.",
    "Ley de conservación.",

    "Sustancia.",
    "Sustancia inorgánica.",
    "Sustancia química.",
    "Sustancia simple.",
    "Sustancia corrosiva.",
    "Sustancia peligrosa.",
    "Salinidad.",
    "Elemento.",
    "Elemento químico esencial.",
    "Elementos transuránicos.",
    "Elemento químico.",
    "Henry Cavendish.",
    "Carl Wilhelm Scheele.",
    "Andrés Manuel del Río.",
    "Compuestos orgánicos persistentes.",
    "Compuesto iónico.",
    "Compuesto químico.",
    "Compuesto orgánico.",
    "Modelo atómico.",
    "Modelo atómico de Bohr.",
    "Niels Bohr.",
    "Átomo.",
    "Átomos en moléculas.",
    "Modelo atómico de Rutherford.",
    "Modelo atómico de Thomson.",
    "Modelo atómico de Dalton.",
    "Modelo atómico.",
    "Unidad de masa atómica.",
    "Número atómico.",
    "Peso atómico.",
    "Historia de la teoría atómica.",
    "Masa atómica.",
    "Enlace químico.",
    "Electrón.",
    "Electrón de valencia.",
    "Electronegatividad.",
    "Ion.",
    "Ion poliatómico.",
    "Ion hidronio.",
    "Ionización.",
    "Enlace iónico.",
    "Compuesto iónico.",
    "Fuerza iónica.",
    "Equilibrio iónico.",
    "Gilbert N. Lewis.",
    "Regla del octeto.",
    "Catión.",
    "Anión.",
    "Enlace covalente.",
    "Enlace metálico.",
    "Elemento químico.",
    "Descubrimiento de los elementos químicos.",
    "Molécula.",
    "Propiedad química.",
    "México prehispánico.",
    "Mercurio.",
    "Oro.",
    "Oro blanco.",
    "Edad de los Metales.",
    "Sólido.",
    "Maleabilidad.",
    "Conductividad.",
    "Conductividad térmica.",
    "Conductividad eléctrica.",
    "Reducción-oxidación.",
    "Aluminio.",
    "Enlace metálico.",
    "Ductilidad.",
    "Edad de Piedra.",
    "Reducción.",
    "Potencial de reducción.",
    "Reutilización.",
    "Reciclaje de pilas y baterías.",
    "Reciclaje de computadoras.",
    "Reciclaje.",
    "Reciclaje de aluminio.",
    "Materiales reciclados.",
    "Stanislao Cannizzaro.",
    "Mendelevio.",
    "Masa y energía en la relatividad especial.",
    "Masa atómica.",
    "Ley de las proporciones múltiples.",
    "Ley de Gay-Lussac.",
    "Louis Joseph Gay-Lussac.",
    "Molécula diatómica.",
    "Johann Wolfgang Döbereiner.",
    "Alexandre-Emile Béguyer de Chancourtois.",
    "Julius Lothar Meyer.",
    "Molécula diatómica.",
    "Tabla periódica de los elementos.",
    "Halógeno.",
    "Halogenación.",
    "Espectro de emisión.",
    "Espectro.",
    "Espectro atómico.",
    "Espectro de absorción.",
    "Masa atómica.",
    "Número atómico.",
    "Química.",
    "Carbono.",
    "Hidrógeno.",
    "Oxígeno.",
    "Nitrógeno.",
    "Fósforo.",
    "Azufre.",
    "Enlace carbono-hidrógeno.",
    "Enlace carbono-oxígeno.",
    "Ciclo del nitrógeno.",
    "Enlace químico.",
    "Enlace iónico.",
    "Enlace covalente.",
    "Enlace iónico.",
    "Enlace covalente.",
    "Compuesto iónico.",
    "Agua.",

    "Ecuación química.",
    "Reacción.",
    "Reacción química.",
    "Reacción endotérmica.",
    "Reacción exergónica.",
    "Reacción exotérmica.",
    "Reacciones de aldehídos.",
    "Reacción en cadena.",
    "Reacción irreversible.",
    "Reacción endergónica.",
    "Tiempo de reacción.",
    "Reacción de síntesis.",
    "Reacción de adición.",
    "Reacción de condensación.",
    "Velocidad de reacción.",
    "Reacción de eliminación.",
    "Caloría.",
    "Energía.",
    "Energía mecánica.",
    "Energía electromagnética.",
    "Energía radiante.",
    "Energía nuclear.",
    "Unicef (Fondo de las Naciones Unidas para la Infancia).",
    "Índice de masa corporal (IMC).",
    "Plato del buen comer.",
    "Proteína.",
    "Proteína de soya.",
    "Estructura de las proteínas.",
    "Estructura secundaria de las proteínas.",
    "Metabolismo de los carbohidratos.",
    "Lípido.",
    "Ácido graso.",
    "Grasa.",
    "Grasa alimentaria.",
    "Vitaminas hidrosolubles.",
    "Vitaminas liposolubles.",
    "Suplemento vitamínico.",
    "Revolución química.",
    "Gilbert N. Lewis.",
    "Linus Pauling.",
    "Biología molecular.",
    "Revolución química.",
    "Electronegatividad.",
    "Nube de electrones.",
    "Cadena de transporte de electrones.",
    "Notación científica.",
    "Lupa.",
    "Nivel microscópico.",
    "Microscopio óptico.",
    "Microscopio electrónico.",
    "Microscopio electrónico de transmisión.",
    "Microscopio electrónico de barrido.",
    "Difracción (física).",
    "Mol.",
    "Unidad de masa atómica.",
    "Unidades de masa.",
    "Balanza.",
    "Balanza de torsión.",
    "Masa molar.",

    "Ácidos y bases de Lewis.",
    "Protón.",
    "Ecuación de Arrhenius.",
    "Svante August Arrhenius.",
    "Ácido débil.",
    "Ácido fuerte.",
    "Ácido fumárico.",
    "Ácido fusídico.",
    "Acidez.",
    "PH.",
    "Antiácido.",
    "Fiambre.",
    "Reducción-oxidación.",
    "Estado de oxidación.",
    "Óxido.",
    "Valoración redox.",
    "Reducción.",
    "Corriente eléctrica.",
    "Carga eléctrica.",
    "Átomo.",

    "Efecto térmico de memoria (polímeros).",
    "Química de los polímeros.",
    "Polímero.",
    "Extrusión de polímero.",
    "Química en México.",
    "Mario Molina.",
    "Luis Ernesto Miramontes.",
    "Andrés Manuel del Río.",
    "Fertilizante.",
    "Plaguicida.",
    "Cosmético.",
    "Cosmética.",
    "Mesoamérica.",
    "Cronologías de Mesoamérica.",
    "Cronologías de Mesoamérica.",
    "Arte precolombino de Mesoamérica.",
    "Basamentos piramidales de Mesoamérica.",
    "Arquitectura mesoamericana.",
    "Arte.",
    "Restauración.",
    "Conservación y restauración.",
    "Conservación.",
    "Proceso químico.",
    "Derivado del petróleo.",
    "Petróleos Mexicanos.",
    "Refinación del petróleo.",
    "Nacionalización de suministros de petróleo.",
    "Origen inorgánico del petróleo.",
    "Reservas de petróleo en México."
]
