#!/usr/bin/env python
# -*- coding: utf-8 -*-

my_articles = [
    "Desplazamiento.",
    "Reacción de desplazamiento.",
    "Modulación por desplazamiento de amplitud.",
    "Modulación por desplazamiento de frecuencia.",
    "Ley de desplazamiento de Wien.",
    "Efecto desplazamiento.",
    "Registro de desplazamiento.",
    "Curvatura (Desplazamiento).",
    "Desplazados internos.",
    "Trayectoria.",
    "Trayectoria balística.",
    "Distancia.",
    "Vector.",
    "Vector de distancias.",
    "Como correr trayectos más largos y a mayor velocidad.",
    "Distancia.",
    "Vector unitario.",
    "Velocidad.",
    "Velocidad relativa.",
    "Velocidad angular.",
    "Desplazamiento.",
    "Reacción de desplazamiento.",
    "Modulación por desplazamiento de amplitud.",
    "Modulación por desplazamiento de frecuencia.",
    "Ley de desplazamiento de Wien.",
    "Efecto desplazamiento.",
    "Registro de desplazamiento.",
    "Curvatura (Desplazamiento).",
    "Desplazados internos.",
    "Tiempo.",
    "Espacio-tiempo.",
    "Gráfica.",
    "Escala gráfica.",
    "Posición.",
    "Movimiento.",
    "Movimiento oscilatorio.",
    "Movimiento curvilíneo.",
    "Onda.",
    "Onda mecánica.",
    "Onda sonora.",
    "Onda cuadrada.",
    "Onda longitudinal.",
    "Onda plana.",
    "Onda transversal.",
    "Longitud de onda.",
    "Propagación de ondas.",
    "Sonido.",
    "Barrera del sonido.",
    "Velocidad del sonido.",
    "Período de oscilación.",
    "Oscilación.",
    "Frecuencia modulada.",
    "Frecuencímetro.",
    "Frecuencia de resonancia.",
    "Frecuencia.",
    "Modulación por desplazamiento de frecuencia.",
    "Bandas de frecuencia.",
    "Longitud.",
    "Longitud de onda.",
    "Onda longitudinal.",
    "Amplitud modulada.",
    "Modulación por desplazamiento de amplitud.",
    "Modulación de amplitud en cuadratura.",
    "Propagación de ondas.",
    "Rapidez.",
    "Nivel de presión sonora.",
    "Galileo Galilei.",
    "Aristóteles.",
    "Caída libre.",
    "Plano inclinado.",
    "Galileo Galilei.",
    "Aceleración.",
    "Velocidad.",
    "Movimiento uniformemente acelerado.",
    "Movimiento rectilíneo uniformemente acelerado.",
    "Movimiento circular uniformemente acelerado.",
    "Movimiento circular uniforme.",
    "Aceleración.",
    "Velocidad.",
    "Movimiento uniformemente acelerado.",
    "Movimiento rectilíneo uniformemente acelerado.",
    "Movimiento circular uniformemente acelerado.",
    "Movimiento circular uniforme.",
    "Interpretación.",
    "Representación.",
    "Gráfica.",
    "Velocidad.",
    "Fuerza.",
    "Interacción.",
    "Interacción electromagnética.",
    "Vector.",
    "Vector de distancias.",
    "Distancia.",
    "Medición.",
    "Instrumento de medición.",
    "Dinamómetro.",
    "Llave dinamométrica.",
    "Interacciones fundamentales.",
    "Distancia.",
    "Fuerza.",
    "Vector.",
    "Vector de distancias.",
    "Equilibrio.",
    "Diagrama.",
    "Fuerza.",
    "NEW_BLOQUE",
    "Isaac Newton.",
    "Leyes de Newton.",
    "Método de Newton.",
    "Inercia.",
    "Masa inercial.",
    "Masa.",
    "Unidades de masa.",
    "Leyes de Newton.",
    "Mecánica newtoniana.",
    "Newton metro.",
    "Fuerza.",
    "Masa.",
    "Aceleración.",
    "Leyes de Newton.",
    "Magnitud.",
    "Magnitud física.",
    "Reacción.",
    "Constante de gravitación universal.",
    "Ley de gravitación universal.",
    "Energía gravitatoria.",
    "Intensidad del campo gravitatorio.",
    "Masa gravitacional.",
    "Singularidad gravitacional.",
    "Campo gravitatorio.",
    "Onda gravitacional.",
    "Caída libre.",
    "Ecuaciones para un cuerpo en caída libre.",
    "Leyes de Newton.",
    "Movimientos de la Tierra.",
    "Galileo Galilei.",
    "Isaac Newton.",
    "Ley de gravitación universal.",
    "Mecánica.",
    "Energía.",
    "Energía mecánica.",
    "Energía hidráulica.",
    "Energía geotérmica.",
    "Energía eólica.",
    "Energía solar fotovoltaica.",
    "Energía solar térmica.",
    "Energía gravitatoria.",
    "Energía interna.",
    "Energía electromagnética.",
    "Energía cinética.",
    "Energía potencial.",
    "Energía solar.",
    "Energía lumínica.",
    "Energía cinética.",
    "Energía potencial.",
    "Energía potencial electrostática.",
    "Conservación de la energía.",
    "NEW_BLOQUE",
    "Partícula.",
    "Partículas en suspensión.",
    "Partícula elemental.",
    "Partícula subatómica.",
    "Modelo estándar de física de partículas.",
    "Carga eléctrica.",
    "Gas ideal.",
    "Constante universal de los gases ideales.",
    "Ley de los gases ideales.",
    "Cuerpo negro.",
    "Demócrito.",
    "Aristóteles.",
    "Isaac Newton.",
    "Rudolf Clausius.",
    "Relación de Clausius-Clapeyron.",
    "James Clerk Maxwell.",
    "Ley de Stefan-Boltzmann.",
    "Constante de Boltzmann.",
    "Ludwig Boltzmann.",
    "Las ecuaciones de Mawell.",
    "Modelo estándar de física de partículas.",
    "Partícula.",
    "Masa.",
    "Masa y energía en la relatividad especial.",
    "Masa inercial.",
    "Volumen.",
    "Densidad.",
    "Fuerza.",
    "Área.",
    "Principio de Pascal.",
    "Pascal.",
    "Temperatura",
    "Temperatura absoluta",
    "Calor.",
    "Calor específico.",
    "Calor húmedo.",
    "Calor latente.",
    "Calor sensible.",
    "Calor seco.",
    "Calorímetro.",
    "Calorimetría.",
    "Ecuación del calor.",
    "Conducción de calor.",
    "Teoría calórica.",
    "Transferencia de calor.",
    "Poder calorífico.",
    "Capacidad calorífica o capacidad térmica.",
    "Presión.",
    "Temperatura.",
    "Temperatura crítica.",
    "Temperatura atmosférica.",
    "Temperatura absoluta.",
    "Condiciones normales de presión y temperatura.",
    "Coeficiente de temperatura.",
    "Presión parcial.",
    "Presión osmótica.",
    "Capacidad calorífica.",
    "Poder calorífico.",
    "Equilibrio.",
    "Equilibrio térmico.",
    "Transferencia.",
    "Transferencia de calor.",
    "Temperatura.",
    "Conservación de la energía.",
    "Energía cinética.",
    "Energía potencial.",
    "Energía potencial electrostática.",
    "Conservación de la energía.",
    "NEW_BLOQUE",
    "Modelo atómico.",
    "Modelo atómico de Rutherford.",
    "Modelo atómico de Schrödinger.",
    "Modelo atómico de Bohr.",
    "Modelo atómico de Thomson.",
    "Modelo atómico de Sommerfeld.",
    "Modelo atómico de Dalton.",
    "Modelo atómico.",
    "Núcleo.",
    "Núcleo atómico.",
    "Protón.",
    "Neutrón.",
    "Electrón.",
    "Capa electrónica.",
    "Electronegatividad.",
    "Cadena de transporte de electrones.",
    "Electrostática.",
    "Descarga electrostática.",
    "Carga eléctrica.",
    "Electrización.",
    "Carga por inducción.",
    "Pérdida de carga.",
    "Ley de Coulomb.",
    "Charles-Augustin de Coulomb.",
    "Resistencia eléctrica.",
    "Aislamiento eléctrico.",
    "Corriente eléctrica.",
    "Carga eléctrica.",
    "Conducción.",
    "Conductancia eléctrica.",
    "Conductímetro.",
    "Conductividad eléctrica.",
    "Conducción eléctrica.",
    "Conductor eléctrico.",
    "Aislante.",
    "Dieléctrico.",
    "Rigidez dieléctrica.",
    "Constante dieléctrica.",
    "Pila eléctrica.",
    "Reciclaje de pilas y baterías.",
    "Pila AAA.",
    "Historia de la pila.",
    "Pila AA.",
    "Electromagnetismo.",
    "Interacción electromagnética.",
    "Ley de Faraday de la electrólisis.",
    "Ley de Faraday.",
    "Michael Faraday.",
    "Campo magnético.",
    "Campo magnético rotativo.",
    "Campo magnético terrestre.",
    "Galvanómetro.",
    "Galvanoplastia.",
    "Electromagnetismo.",
    "Electroimán.",
    "Generador eléctrico.",
    "Generador síncrono.",
    "Transformador.",
    "Transformador flyback.",
    "Espectro.",
    "Refracción.",
    "Índice de refracción.",
    "Radiación electromagnética.",
    "Radiación electromagnética y salud.",
    "Espectro.",
    "Radiación infrarroja.",
    "Radiación ultravioleta.",
    "Rayos X.",
    "Cristalografía de rayos X.",
    "Wilhelm Röntgen.",
    "Rayos gamma.",
    "Brote de rayos gamma.",
    "Astronomía de rayos gamma.",
    "Astronomía de Rayos-X.",
    "Observatorio Chandra de Rayos-X.",
    "Difracción (física).",
    "Interferencia electromagnética.",
    "Fotón.",
    "Fotónica.",
    "Energía electromagnética.",
    "Electricidad.",
    "Energía electromagnética.",
    "Energía electromagnética.",
    "Radiación electromagnética.",
    "Radiación electromagnética y salud.",
    "NEW_BLOQUE",
    "Big Bang.",
    "Cronología del Big Bang.",
    "Efecto Doppler.",
    "Cosmología física.",
    "Cosmología.",
    "Cosmología budista.",
    "Tamaño de los cuerpos celestes.",
    "Cosmos.",
    "Cosmografía.",
    "Galaxia.",
    "Galaxia elíptica.",
    "Galaxia del Triángulo.",
    "Galaxia de Andrómeda.",
    "Galaxia irregular.",
    "Galaxy Nexus.",
    "Formación y evolución de las galaxias.",
    "Vía Láctea.",
    "Colisión Vía Láctea-Andrómeda.",
    "Sol.",
    "El Sol.",
    "Sistema Solar.",
    "Cuerpo menor del Sistema Solar.",
    "Definición de planeta.",
    "Saturno (planeta).",
    "Interacción de galaxias.",
    "Solsticio.",
    "Solsticio de invierno.",
    "Solsticio de verano.",
    "Erupción solar.",
    "Variación solar.",
    "Constante solar.",
    "Mancha solar.",
    "Viento solar.",
    "Luz solar.",
    "Formación y evolución del sistema solar.",
    "Planeta.",
    "Planeta a simple vista.",
    "Planeta extrasolar.",
    "Planeta terrestre.",
    "Mercurio (planeta).",
    "Marte (planeta).",
    "Urano (planeta).",
    "Venus (planeta).",
    "Neptuno (planeta).",
    "Astronomía de posición.",
    "Astronomía maya.",
    "Astronomía.",
    "Astrónomo.",
    "Historia de la astronomía.",
    "Símbolos astronómicos.",
    "Unidad astronómica.",
    "Objeto astronómico.",
    "Astronomía visible.",
    "Astronomía ultravioleta.",
    "Astronomía observacional.",
    "Astronomía amateur.",
    "Astronomía infrarroja.",
    "Astronomía rayos gamma.",
    "Astronomía árabe.",
    "Astronomía  maya.",
    "Astronomía de rayos-X.",
    "Astronomía babilónica.",
    "Astronomía.",
    "Astrónomo.",
    "Astronomía china.",
    "Símbolos astronómicos.",
    "Coordenadas baricéntricas (astronomía).",
    "Telescopio espacial Spitzer.",
    "Telescopio refractor.",
    "Telescopio.",
    "Telescopio espacial Hubble.",
    "Telescopio reflector.",
    "Historia del telescopio.",
    "Gran Telescopio Milimétrico.",
    "Mira telescópica."
]
